### ISSUE TITLE
error: Error from onstar.  (Onstar timeout)

### ISSUE THREAD

**Issue by kallisti5** [michaelwoods/onstar2mqtt#103]
Valid onstar_username, onstar_password, onstar_pin, onstar_vin provided.  Getting an "error: Error" from onstar.

I've attached the error from onstar2mqtt and omitted "data", the vin, and the bearer tokens.

[onstar.txt](https://github.com/michaelwoods/onstar2mqtt/files/7782668/onstar.txt)

**Comment by kallisti5** [comment]
I made sure to keep the json valid for the most part... Onstar throws up a lot of junk via rest :-|

**Comment by kallisti5** [comment]
Ugh. Just the vehicle falling asleep.  I swear Onstar shuts down after < 36-48 hours in the Bolt EV.

I looked through my alldata subscription this evening... Onstar's fuse is powered through the KR104A "battery saver relay".   It looks like the K9 "Body Control Module" tells the relay to shutoff after some conditions are met.  (time... current?)

![fuses](https://user-images.githubusercontent.com/100110/147719499-8f731283-5b95-4308-a7e6-35dd061ffe61.png)


I wonder if the conditions could be "tweaked"?

**Comment by kallisti5** [comment]
... or I guess someone could hold the battery saver relay closed somehow.  Maybe jumper pin 5 of the relay to pin 3, or pull the 10A onstar fuse and jumper it somewhere else with a constant 12v.

**Comment by kallisti5** [comment]
Hell.  I think I just figured this one out.

```
11:14 - error
0:14 - error
Powered car on
1:14 - success
2:15 - success
3:14 - success
4:14 - success
5:13 - success
6:13 - success
7:13 - success
8:13 - success
9:13 - error
10:13 - error
11:13 - error
12:13 - error
```

You can request diagnostics 8 times between starts and stops of the vehicle.  After 8 times it begins to error out until you start / stop the vehicle.  For full context.. i'm on the Onstar "free-for-five years mobile command" package.

**Comment by kallisti5** [comment]
Observations while in the "Onstar 8-request lockout"

* Unlocking and relocking the doors via remote - get_diagnostic request still failing
* Physically opening and closing doors - get_diagnostic request still failing
* Issuing vehicle commands through API (lock, unlock) - Functional, but get_diagnostic request still failing afterwards
* Plugging vehicle into a Level 2 charger - get_diagnostic request still failing
* Getting into vehicle, powering car on - get_diagnostic requests working again

**Comment by kallisti5** [comment]
In the first onstar request, the following is included...
```
"data":{"commandResponse":{"requestTime":"2021-12-28T03:40:56.236Z","status":"inProgress","type":"diagnostics","url":"https://api.gm.com/api/v1/account/vehicles/VIN_HIDDEN/requests/31238384973"}},"headers":{"cache-control":"public, max-age=5","content-length":"182","content-type":"application/json;charset=UTF-8","date":"Tue, 28 Dec 2021 03:41:50 GMT","gccx-transactionid":"XXX","server":"Layer7-API-Gateway"}
```

So.. when in this 8-request-block state, Onstar appears to give:

error: Error... "status":"inProgress"

**Comment by michaelwoods** [comment]
Thanks a lot for looking into this. I couldn't figure out a pattern to it, I guess when debugging I'm frequently requesting diags so it seemed liked rate limiting. I'll try to confirm this on my side too.

I wonder if a remote start command followed by a cancel would help. Though, I seem to recall that the Onstar SMS for charging complete only comes through when powering on the vehicle.

**Comment by kallisti5** [comment]
I'm less sure now. The observations about what will get OnStar working again are 100% correct.... but the 8 request pattern was later disproved.

Honestly after all of this I've just about given up using OnStar. GM sucks.

Ordered an OVMS to replace it.

**Comment by Entropy512** [comment]
"Ordered an OVMS to replace it." - Have you found a source for radio connectors?  (Or any connector that is wired to the "dirty" telematics buses, radio is the most accessible) The part number listed in the service manual is unobtainium.

Looking at the OVMS, it has an OBD2 connector, so it isn't going to work.  The SDGM blocks any telematics command that originates from that connector.  You can wake up the buses with an SWCAN/LS-CAN HV wake signal, but if you put any start/unlock/whatever command onto the SWCAN bus it won't respond.

OVMS does not even appear to have SWCAN support unlike the Macchina M2 and P1?

**Comment by kallisti5** [comment]
Never heard of the Macchina :-(   Wish I knew about it before getting the OVDS since that's more inline what I wanted (ESP32 + Wifi+LTE)

My biggest use case for Onstar, OVMS, etc is to remotely check battery levels.   Since Level 1 / 2 doesn't know SoC, the only place to get it is via the vehicle itself.  (Ideally Onstar... except it's been *REALLY* unreliable).    The unreliability of Onstar paired with the *steep* fees when the free trial runs out is the driver for most of this.

Remote pre-condition commands are nice, but my remote also works well enough for that stuff.

**Comment by Entropy512** [comment]
Hmm.  Not sure if an HV wakeup will cause battery data to show up on any of the buses that can be grabbed passively.

Interestingly during a charge cycle, most of the car's electronics go to sleep (including the buses going inactive) for very long periods of time.

**Comment by kallisti5** [comment]
I just disabled OnStar in my car.. went pretty smoothly.   That was the real solution for me.

Made a filler panel here with some quick instructions:
https://www.thingiverse.com/thing:5199130

I just realized I never actually submitted the OVMS order.

I'm going to get the Macchina as soon as its in stock since it offers GMLAN capability.

Thinking I might pull the onstar module and hack the Macchina in there (using the connector from the Onstar box).  Should have full access to *everything* CAN from the OnStar connectors.

**Comment by kallisti5** [comment]
Disabling OnStar breaks the in-car microphone during calls :-|   Looks like the OnStar module taps into the microphone signal and amplifies it for the radio.


![onstar](https://user-images.githubusercontent.com/100110/150449969-a7b219c1-774c-4139-9c6d-181bdde579b7.png)

**Comment by kallisti5** [comment]
anyway.. i'm off topic now on this one.  Going to close it out.   Sorry for the spam.

The Onstar timeouts are still an issue, but the solution looks wholly dependent on GM fixing Onstar
