### ISSUE TITLE
Configurable request delay

### ISSUE THREAD

**Issue by kallisti5** [michaelwoods/onstar2mqtt#104]
As witnessed in #103 , it appears users (Maybe only with the 5-year-free "EV Mobile Command" package?) are limited to pulling diagnostic information 8 times before powering their vehicle on (and resetting the counter).

Requests for diagnostics after 8 attempts will begin returning with "error: Error" until the vehicle is powered on again.

With the above in mind, the threshold should likely be a default of 2 hours between checks, and adjustable via environment variables to the container.

**Comment by michaelwoods** [comment]
@kallisti5 this is actually already available via the env var `ONSTAR_REFRESH` that defaults to 30min.

I'll have to add that into the README.
