### ISSUE TITLE
Documentation Request : publish the list of available information and commands

### ISSUE THREAD

**Issue by ehran** [michaelwoods/onstar2mqtt#131]
Great dev, I imported this in my HA instance but struggled to put in place the dashboard as it was presented in your screenshot, after many tries and fidgeting with the scripts using the examples provided in HA-MQTT.md
I gathered that
payload: '{"command": "cancelStartVehicle"} - cancels the start of the vehicule previously started with '{"command": "startVehicle"}'
payload: '{"command": "lockDoors"}' locks the doors
 payload: '{"command": "UnlockDoors"}' unlocks the doors

I failed to find a place where all the commands were listed... this would be a nice thing to have in addition to the files in git.

**Comment by michaelwoods** [comment]
I hope this helps

 https://github.com/michaelwoods/onstar2mqtt/blob/main/HA-MQTT.md#commands
