### ISSUE TITLE
HomeAssistant : no unique ID

### ISSUE THREAD

**Issue by ehran** [michaelwoods/onstar2mqtt#132]
I am running onstar2mqtt on a synology NAS via the docker plugin.
All the environement variables are filled in , onstar2mqtt grabs everything and pushes it to MQTT. ONSTAR_DEVICEID is also in the environement variables.
I have 2 instances of onstar2mqtt running, each for a different car, but same onstar account. (different VIN, different generated devideID)
I can read everything in Home Assistant but the entities names are doubled (i.e. ev_plug_state and ev_plug_state_2)

However : 
- MQTT does not show me the entities as belonging to a single device, I do not see more devices in the MQTT integration
- but I can access all the information directly from the entities menu, it just doesnt seem to recognise it coming from MQTT
- and all these entities report not having a unique ID.

**Comment by FireBall1725** [comment]
+1 for adding unique id's

**Comment by FireBall1725** [comment]
Created a PR that will fix this https://github.com/michaelwoods/onstar2mqtt/pull/165

**Comment by FireBall1725** [comment]
@michaelwoods thanks for accepting the PR to fix this issue, just wondering if you knew when you might cut a release, would love to get my kube cluster updated with this fix so i could re-enable collecting data from my vehicle.

**Comment by FireBall1725** [comment]
@ehran if your still waiting on the fix i have pushed it to my dockerhub while waiting for @michaelwoods to cut a release. https://hub.docker.com/r/fireball1725/onstar2mqtt. It seems to be working, i'm using it to read my vehicle info

**Comment by michaelwoods** [comment]
@FireBall1725 v1.4 is out, thanks again.
