### ISSUE TITLE
Call to onstar2MQTT returning an error after car idle for 10+ hours

### ISSUE THREAD

**Issue by ehran** [michaelwoods/onstar2mqtt#133]
I am making calls for 2 different VINs, one works well, the other returns errors. Same configuration exactly except that the VIN is different. They are both returning values that can be read in HA but #1 ends its script with 'info: Updates complete, sleeping.' where #2 ends its script with an insanely long suite of what seems to be one long error message starting with : 'error: Error {"error":{"request":{"authRequired":true,"body":"{}","checkRequestStatus":true,"contentType":"application/json; charset=UTF-8","headers":{},"method.......'

Only difference I can see between the 2 VIN : one is for a car coming from the US (#1), one is for a car coming from Canada (#2).

**Comment by ehran** [comment]
attaching the text returned, VIN hidden
[new 3.txt](https://github.com/michaelwoods/onstar2mqtt/files/8080811/new.3.txt)

sounds related to https://github.com/michaelwoods/onstar2mqtt/issues/103 but now quite sure...

**Comment by ehran** [comment]
Also getting the same when sending a command (i.e. getlocation)

error: Command error {"command":"getLocation","err":{"request":{"authRequired":true,"body":"{}","checkRequestStatus":true,"contentType":"application/json; charset=UTF-8","headers":{},"method":0,"upgradeRequired":false,"url":"https://api.gm.com/api/v1/account/vehicles/VIN_HIDDEN/requests/32134404259"},"response":{"config":{"headers":{"Accept":"application/json","Accept-Encoding":"br, gzip, deflate","Accept-Language":"en-US","Authorization":"Bearer eyJqa3UiOiJodHRwczovL3NlYy1hdXRoei1tb2JpbGUubmEub25zdGFyLmNwaS5nbS5jb20vYXBpL3YxL29hdXRoL2tleVNldHMvIiwia2lkIjoibW9iaWxlLWF1dGh6LWp3dC10b2tlbi1wcm9kLW5hLTA4MDQyMDIyLTEiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiIxMjU2ZTZmMi1lY2QyLTRiMGYtOThlMS1jYjUyOTA2NWU4MGMiLCJpYXQiOjE2NDUwMjU5NDUsInN1YiI6IjU4YzU3MGIxLTgwMDMtNDI0MC1hODFkLTY0ZWNkZWUwNWRiYyIsImlzcyI6Imh0dHBzOi8vc2VjLWF1dGh6LW1vYmlsZS5uYS5vbnN0YXIuY3BpLmdtLmNvbSIsImF1ZCI6ImN2Y19wcm9kIiwiZXhwIjoxNjQ1MDI3NzQ0LCJ2ZXIiOjEuMywic2NvcGUiOiJnbW9jIGNvbW1lcmNlIHVzZXJfdHJhaWxlciBvbnN0YXIgcm9sZV9vd25lciIsInBhaSI6Ik9NTklCVVNfQ1ZZIiwidHlwIjoiYmVhcmVyIiwiZGNpIjoiODM2ZGYyMzktMGNiYi00ZGFjLWE0ZTUtOGQyNzczODIwMDM3IiwicGVyIjoiQUFBQUFBTUFBQUFBQUFBQVlBQUFBQUFBQUFBQUFBQUFRQUFBd0FBQUFBQUFBQUFBQUFBQUFBPT0iLCJjaGFuIjoibW9iaWxlIiwidmVocyI6W3sidmluIjoiMUcxRlg2UzA5SDQxNzA3NDciLCJwZXIiOiJBQUJBQUFBQUFBQUFBQUFBQUFRR0FBQXdBQUNBQUFBQUFBQUFHQUFBQUFBQUFBQUFBQUFBQUE9PSJ9LHsidmluIjoiMUcxRlg2UzA4SDQxMjczODYiLCJwZXIiOiJBQUJBQUFBQUFBQUFBQUFBQUFRR0FBQXdBQUNBQUFBQUFBQUFHQUFBQUFBQUFBQUFBQUFBQUE9PSJ9XX0.ZQiT7iBp329vPvo7q4Q9QXCty41UhIMYT8C49gXUWuKU0s8bPPxRNfgluJq44Gpi_Zd3mfzQuajhwsI2aMdLeZSjTk-nguFEvyLF0UKkUizt0b6kFQjJID-61bbd_FNdq-LzKJA8aRKH0BsdWiLa8LcX8b6zKRz_a-4_baDjzuRdqJNU8ChK2Mjv7UHWsMv4RCbByUaSfqJ7PaoFgmGIF6pRvefyi3S18wtnesPFtVpehe89d6jgti6it3LUYL4is9kjSkY0AFJA73qgnVq83esz2f9mzPRcjUtW50ncnK5ufNUllcaKxp6gMq5n0rKCjvhonaAYF1kYm1jFX3NUWg","Connection":"keep-alive","Content-Type":"application/json; charset=UTF-8","Host":"api.gm.com","User-Agent":"Mozilla/5.0 (Linux; U; Android 9; en-US; Google Pixel 2 Build/PI)"},"maxBodyLength":-1,"maxContentLength":-1,"method":"get","timeout":0,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"https://api.gm.com/api/v1/account/vehicles/VIN_HIDDEN/requests/32134404259","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN"},"data":{"commandResponse":{"requestTime":"2022-02-16T15:39:09.407Z","status":"inProgress","type":"location","url":"https://api.gm.com/api/v1/account/vehicles/VIN_HIDDEN/requests/32134404259"}},"headers":{"cache-control":"public, max-age=5","content-length":"179","content-type":"application/json;charset=UTF-8","date":"Wed, 16 Feb 2022 15:40:07 GMT","gccx-transactionid":"0000017ee754edf6-1838132","server":"Layer7-API-Gateway"},"request":{"_contentLength":0,"_defaultKeepAlive":true,"_ended":true,"_events":{},"_eventsCount":7,"_hasBody":true,"_header":"GET /api/v1/account/vehicles/VIN_HIDDEN/requests/32134404259 HTTP/1.1\r\nAccept: application/json\r\nAccept-Language: en-US\r\nContent-Type: application/json; charset=UTF-8\r\nHost: api.gm.com\r\nConnection: keep-alive\r\nAccept-Encoding: br, gzip, deflate\r\nUser-Agent: Mozilla/5.0 (Linux; U; Android 9; en-US; Google Pixel 2 Build/PI)\r\nAuthorization: Bearer eyJqa3UiOiJodHRwczovL3NlYy1hdXRoei1tb2JpbGUubmEub25zdGFyLmNwaS5nbS5jb20vYXBpL3YxL29hdXRoL2tleVNldHMvIiwia2lkIjoibW9iaWxlLWF1dGh6LWp3dC10b2tlbi1wcm9kLW5hLTA4MDQyMDIyLTEiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiIxMjU2ZTZmMi1lY2QyLTRiMGYtOThlMS1jYjUyOTA2NWU4MGMiLCJpYXQiOjE2NDUwMjU5NDUsInN1YiI6IjU4YzU3MGIxLTgwMDMtNDI0MC1hODFkLTY0ZWNkZWUwNWRiYyIsImlzcyI6Imh0dHBzOi8vc2VjLWF1dGh6LW1vYmlsZS5uYS5vbnN0YXIuY3BpLmdtLmNvbSIsImF1ZCI6ImN2Y19wcm9kIiwiZXhwIjoxNjQ1MDI3NzQ0LCJ2ZXIiOjEuMywic2NvcGUiOiJnbW9jIGNvbW1lcmNlIHVzZXJfdHJhaWxlciBvbnN0YXIgcm9sZV9vd25lciIsInBhaSI6Ik9NTklCVVNfQ1ZZIiwidHlwIjoiYmVhcmVyIiwiZGNpIjoiODM2ZGYyMzktMGNiYi00ZGFjLWE0ZTUtOGQyNzczODIwMDM3IiwicGVyIjoiQUFBQUFBTUFBQUFBQUFBQVlBQUFBQUFBQUFBQUFBQUFRQUFBd0FBQUFBQUFBQUFBQUFBQUFBPT0iLCJjaGFuIjoibW9iaWxlIiwidmVocyI6W3sidmluIjoiMUcxRlg2UzA5SDQxNzA3NDciLCJwZXIiOiJBQUJBQUFBQUFBQUFBQUFBQUFRR0FBQXdBQUNBQUFBQUFBQUFHQUFBQUFBQUFBQUFBQUFBQUE9PSJ9LHsidmluIjoiMUcxRlg2UzA4SDQxMjczODYiLCJwZXIiOiJBQUJBQUFBQUFBQUFBQUFBQUFRR0FBQXdBQUNBQUFBQUFBQUFHQUFBQUFBQUFBQUFBQUFBQUE9PSJ9XX0.ZQiT7iBp329vPvo7q4Q9QXCty41UhIMYT8C49gXUWuKU0s8bPPxRNfgluJq44Gpi_Zd3mfzQuajhwsI2aMdLeZSjTk-nguFEvyLF0UKkUizt0b6kFQjJID-61bbd_FNdq-LzKJA8aRKH0BsdWiLa8LcX8b6zKRz_a-4_baDjzuRdqJNU8ChK2Mjv7UHWsMv4RCbByUaSfqJ7PaoFgmGIF6pRvefyi3S18wtnesPFtVpehe89d6jgti6it3LUYL4is9kjSkY0AFJA73qgnVq83esz2f9mzPRcjUtW50ncnK5ufNUllcaKxp6gMq5n0rKCjvhonaAYF1kYm1jFX3NUWg\r\n\r\n","_headerSent":true,"_keepAliveTimeout":0,"_last":true,"_redirectable":{"_currentRequest":"[Circular]","_currentUrl":"https://api.gm.com/api/v1/account/vehicles/VIN_HIDDEN/requests/32134404259","_ended":true,"_ending":true,"_events":{},"_eventsCount":2,"_options":{"agents":{},"headers":{"Accept":"application/json","Accept-Encoding":"br, gzip, deflate","Accept-Language":"en-US","Authorization":"Bearer eyJqa3UiOiJodHRwczovL3NlYy1hdXRoei1tb2JpbGUubmEub25zdGFyLmNwaS5nbS5jb20vYXBpL3YxL29hdXRoL2tleVNldHMvIiwia2lkIjoibW9iaWxlLWF1dGh6LWp3dC10b2tlbi1wcm9kLW5hLTA4MDQyMDIyLTEiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiIxMjU2ZTZmMi1lY2QyLTRiMGYtOThlMS1jYjUyOTA2NWU4MGMiLCJpYXQiOjE2NDUwMjU5NDUsInN1YiI6IjU4YzU3MGIxLTgwMDMtNDI0MC1hODFkLTY0ZWNkZWUwNWRiYyIsImlzcyI6Imh0dHBzOi8vc2VjLWF1dGh6LW1vYmlsZS5uYS5vbnN0YXIuY3BpLmdtLmNvbSIsImF1ZCI6ImN2Y19wcm9kIiwiZXhwIjoxNjQ1MDI3NzQ0LCJ2ZXIiOjEuMywic2NvcGUiOiJnbW9jIGNvbW1lcmNlIHVzZXJfdHJhaWxlciBvbnN0YXIgcm9sZV9vd25lciIsInBhaSI6Ik9NTklCVVNfQ1ZZIiwidHlwIjoiYmVhcmVyIiwiZGNpIjoiODM2ZGYyMzktMGNiYi00ZGFjLWE0ZTUtOGQyNzczODIwMDM3IiwicGVyIjoiQUFBQUFBTUFBQUFBQUFBQVlBQUFBQUFBQUFBQUFBQUFRQUFBd0FBQUFBQUFBQUFBQUFBQUFBPT0iLCJjaGFuIjoibW9iaWxlIiwidmVocyI6W3sidmluIjoiMUcxRlg2UzA5SDQxNzA3NDciLCJwZXIiOiJBQUJBQUFBQUFBQUFBQUFBQUFRR0FBQXdBQUNBQUFBQUFBQUFHQUFBQUFBQUFBQUFBQUFBQUE9PSJ9LHsidmluIjoiMUcxRlg2UzA4SDQxMjczODYiLCJwZXIiOiJBQUJBQUFBQUFBQUFBQUFBQUFRR0FBQXdBQUNBQUFBQUFBQUFHQUFBQUFBQUFBQUFBQUFBQUE9PSJ9XX0.ZQiT7iBp329vPvo7q4Q9QXCty41UhIMYT8C49gXUWuKU0s8bPPxRNfgluJq44Gpi_Zd3mfzQuajhwsI2aMdLeZSjTk-nguFEvyLF0UKkUizt0b6kFQjJID-61bbd_FNdq-LzKJA8aRKH0BsdWiLa8LcX8b6zKRz_a-4_baDjzuRdqJNU8ChK2Mjv7UHWsMv4RCbByUaSfqJ7PaoFgmGIF6pRvefyi3S18wtnesPFtVpehe89d6jgti6it3LUYL4is9kjSkY0AFJA73qgnVq83esz2f9mzPRcjUtW50ncnK5ufNUllcaKxp6gMq5n0rKCjvhonaAYF1kYm1jFX3NUWg","Connection":"keep-alive","Content-Type":"application/json; charset=UTF-8","Host":"api.gm.com","User-Agent":"Mozilla/5.0 (Linux; U; Android 9; en-US; Google Pixel 2 Build/PI)"},"hostname":"api.gm.com","maxBodyLength":10485760,"maxRedirects":21,"method":"GET","nativeProtocols":{"http:":{"METHODS":["ACL","BIND","CHECKOUT","CONNECT","COPY","DELETE","GET","HEAD","LINK","LOCK","M-SEARCH","MERGE","MKACTIVITY","MKCALENDAR","MKCOL","MOVE","NOTIFY","OPTIONS","PATCH","POST","PRI","PROPFIND","PROPPATCH","PURGE","PUT","REBIND","REPORT","SEARCH","SOURCE","SUBSCRIBE","TRACE","UNBIND","UNLINK","UNLOCK","UNSUBSCRIBE"],"STATUS_CODES":{"100":"Continue","101":"Switching Protocols","102":"Processing","103":"Early Hints","200":"OK","201":"Created","202":"Accepted","203":"Non-Authoritative Information","204":"No Content","205":"Reset Content","206":"Partial Content","207":"Multi-Status","208":"Already Reported","226":"IM Used","300":"Multiple Choices","301":"Moved Permanently","302":"Found","303":"See Other","304":"Not Modified","305":"Use Proxy","307":"Temporary Redirect","308":"Permanent Redirect","400":"Bad Request","401":"Unauthorized","402":"Payment Required","403":"Forbidden","404":"Not Found","405":"Method Not Allowed","406":"Not Acceptable","407":"Proxy Authentication Required","408":"Request Timeout","409":"Conflict","410":"Gone","411":"Length Required","412":"Precondition Failed","413":"Payload Too Large","414":"URI Too Long","415":"Unsupported Media Type","416":"Range Not Satisfiable","417":"Expectation Failed","418":"I'm a Teapot","421":"Misdirected Request","422":"Unprocessable Entity","423":"Locked","424":"Failed Dependency","425":"Unordered Collection","426":"Upgrade Required","428":"Precondition Required","429":"Too Many Requests","431":"Request Header Fields Too Large","451":"Unavailable For Legal Reasons","500":"Internal Server Error","501":"Not Implemented","502":"Bad Gateway","503":"Service Unavailable","504":"Gateway Timeout","505":"HTTP Version Not Supported","506":"Variant Also Negotiates","507":"Insufficient Storage","508":"Loop Detected","509":"Bandwidth Limit Exceeded","510":"Not Extended","511":"Network Authentication Required"},"globalAgent":{"_events":{},"_eventsCount":2,"defaultPort":80,"freeSockets":{},"keepAlive":false,"keepAliveMsecs":1000,"maxFreeSockets":256,"maxSockets":null,"maxTotalSockets":null,"options":{"path":null},"protocol":"http:","requests":{},"scheduling":"fifo","sockets":{},"totalSocketCount":0},"maxHeaderSize":8192},"https:":{"globalAgent":{"_events":{},"_eventsCount":2,"_sessionCache":{"list":["api.gm.com:443::::::::::::::::::"],"map":{"api.gm.com:443::::::::::::::::::":{"data":[48,130,7,76,2,1,1,2,2,3,3,4,2,192,47,4,32,77,73,6,186,208,253,42,142,149,241,74,152,154,36,51,244,26,144,6,25,89,143,198,207,201,104,146,16,41,116,67,198,4,48,115,12,95,97,4,34,90,64,10,118,109,206,49,232,163,74,179,187,71,239,205,244,66,7,208,255,21,155,246,248,83,107,20,233,105,116,197,42,133,238,229,137,117,125,129,220,246,102,161,6,2,4,98,13,26,220,162,4,2,2,28,32,163,130,6,210,48,130,6,206,48,130,5,182,160,3,2,1,2,2,16,8,97,10,132,66,236,115,245,37,42,63,86,109,47,111,191,48,13,6,9,42,134,72,134,247,13,1,1,11,5,0,48,100,49,11,48,9,6,3,85,4,6,19,2,85,83,49,21,48,19,6,3,85,4,10,19,12,68,105,103,105,67,101,114,116,32,73,110,99,49,25,48,23,6,3,85,4,11,19,16,119,119,119,46,100,105,103,105,99,101,114,116,46,99,111,109,49,35,48,33,6,3,85,4,3,19,26,68,105,103,105,67,101,114,116,32,66,97,108,116,105,109,111,114,101,32,67,65,45,50,32,71,50,48,30,23,13,50,49,48,56,49,57,48,48,48,48,48,48,90,23,13,50,50,48,56,49,57,50,51,53,57,53,57,90,48,100,49,11,48,9,6,3,85,4,6,19,2,85,83,49,17,48,15,6,3,85,4,8,19,8,77,105,99,104,105,103,97,110,49,16,48,14,6,3,85,4,7,19,7,68,101,116,114,111,105,116,49,27,48,25,6,3,85,4,10,19,18,71,101,110,101,114,97,108,32,77,111,116,111,114,115,32,76,76,67,49,19,48,17,6,3,85,4,3,19,10,97,112,105,46,103,109,46,99,111,109,48,130,1,34,48,13,6,9,42,134,72,134,247,13,1,1,1,5,0,3,130,1,15,0,48,130,1,10,2,130,1,1,0,206,27,130,143,175,230,1,10,14,124,1,121,72,47,8,209,1,194,5,92,36,224,180,252,219,27,173,171,34,166,118,175,7,253,35,136,138,162,236,117,16,31,64,179,175,162,82,89,31,237,189,64,198,226,76,63,15,185,128,20,147,163,255,74,168,196,58,6,212,8,221,235,67,149,242,221,144,45,29,193,171,250,215,73,247,77,195,10,35,44,110,7,104,21,19,111,157,118,238,227,85,122,137,180,224,0,160,165,44,174,65,204,233,243,158,50,239,19,247,96,31,101,130,240,28,224,221,71,232,239,127,71,15,13,39,88,149,220,68,240,100,0,148,158,40,3,126,117,161,74,60,247,225,185,230,116,64,168,3,32,214,60,11,37,100,174,64,181,42,181,226,98,209,119,176,38,173,69,225,13,34,198,173,171,201,25,185,212,156,16,60,82,78,41,146,194,163,53,22,53,118,222,170,236,223,9,241,119,240,213,16,102,126,244,82,42,44,57,91,163,243,29,82,184,195,235,5,81,58,51,147,191,196,253,73,148,108,55,76,11,209,249,230,69,143,172,10,3,176,51,177,97,51,52,251,19,2,3,1,0,1,163,130,3,122,48,130,3,118,48,31,6,3,85,29,35,4,24,48,22,128,20,192,18,178,40,116,104,70,103,233,112,37,116,26,0,69,91,6,125,92,68,48,29,6,3,85,29,14,4,22,4,20,114,244,133,80,198,51,1,34,252,36,171,217,111,31,20,136,28,16,201,176,48,54,6,3,85,29,17,4,47,48,45,130,31,112,97,112,105,45,108,55,103,45,100,49,109,120,112,122,108,110,46,111,110,115,116,97,114,46,103,109,46,99,111,109,130,10,97,112,105,46,103,109,46,99,111,109,48,14,6,3,85,29,15,1,1,255,4,4,3,2,5,160,48,29,6,3,85,29,37,4,22,48,20,6,8,43,6,1,5,5,7,3,1,6,8,43,6,1,5,5,7,3,2,48,129,129,6,3,85,29,31,4,122,48,120,48,58,160,56,160,54,134,52,104,116,116,112,58,47,47,99,114,108,51,46,100,105,103,105,99,101,114,116,46,99,111,109,47,68,105,103,105,67,101,114,116,66,97,108,116,105,109,111,114,101,67,65,45,50,71,50,46,99,114,108,48,58,160,56,160,54,134,52,104,116,116,112,58,47,47,99,114,108,52,46,100,105,103,105,99,101,114,116,46,99,111,109,47,68,105,103,105,67,101,114,116,66,97,108,116,105,109,111,114,101,67,65,45,50,71,50,46,99,114,108,48,62,6,3,85,29,32,4,55,48,53,48,51,6,6,103,129,12,1,2,2,48,41,48,39,6,8,43,6,1,5,5,7,2,1,22,27,104,116,116,112,58,47,47,119,119,119,46,100,105,103,105,99,101,114,116,46,99,111,109,47,67,80,83,48,121,6,8,43,6,1,5,5,7,1,1,4,109,48,107,48,36,6,8,43,6,1,5,5,7,48,1,134,24,104,116,116,112,58,47,47,111,99,115,112,46,100,105,103,105,99,101,114,116,46,99,111,109,48,67,6,8,43,6,1,5,5,7,48,2,134,55,104,116,116,112,58,47,47,99,97,99,101,114,116,115,46,100,105,103,105,99,101,114,116,46,99,111,109,47,68,105,103,105,67,101,114,116,66,97,108,116,105,109,111,114,101,67,65,45,50,71,50,46,99,114,116,48,12,6,3,85,29,19,1,1,255,4,2,48,0,48,130,1,126,6,10,43,6,1,4,1,214,121,2,4,2,4,130,1,110,4,130,1,106,1,104,0,117,0,70,165,85,235,117,250,145,32,48,181,162,137,105,244,243,125,17,44,65,116,190,253,73,184,133,171,242,252,112,254,109,71,0,0,1,123,94,112,76,188,0,0,4,3,0,70,48,68,2,32,47,208,242,170,230,75,45,171,165,38,183,141,85,99,83,180,89,111,89,185,244,97,103,2,79,108,108,14,169,159,146,8,2,32,89,130,167,83,71,77,160,165,57,127,42,231,99,30,105,121,126,170,121,143,210,201,144,173,237,216,50,38,55,65,49,64,0,118,0,81,163,176,245,253,1,121,156,86,109,184,55,120,143,12,164,122,204,27,39,203,247,158,136,66,154,13,254,212,139,5,229,0,0,1,123,94,112,76,93,0,0,4,3,0,71,48,69,2,32,108,195,126,119,112,11,23,254,119,160,69,221,192,226,77,6,61,114,235,168,29,226,240,90,209,149,252,194,247,176,149,185,2,33,0,254,108,174,169,2,23,172,109,134,156,49,247,106,135,133,40,5,250,181,111,112,137,36,60,227,90,211,97,51,68,11,155,0,119,0,65,200,202,177,223,34,70,74,16,198,161,58,9,66,135,94,78,49,139,27,3,235,235,75,199,104,240,144,98,150,6,246,0,0,1,123,94,112,76,32,0,0,4,3,0,72,48,70,2,33,0,250,236,232,60,159,63,250,72,168,72,210,195,252,38,246,145,129,80,214,205,18,46,161,237,26,5,82,40,253,213,230,93,2,33,0,198,170,242,51,242,255,55,120,68,188,154,117,13,140,152,48,203,96,250,25,186,193,116,201,106,176,23,69,104,115,167,154,48,13,6,9,42,134,72,134,247,13,1,1,11,5,0,3,130,1,1,0,105,208,199,12,200,16,169,197,150,142,189,12,140,113,120,255,118,164,89,7,9,64,17,12,207,3,11,115,35,22,62,235,34,166,157,58,169,53,252,59,120,119,116,145,211,225,73,205,62,252,53,163,248,59,80,220,249,101,123,82,196,195,92,200,2,102,130,104,92,213,28,19,251,21,125,118,161,65,123,82,187,218,58,63,229,64,194,210,197,126,0,119,227,183,126,161,17,5,77,90,115,34,183,68,47,1,44,201,110,195,68,82,60,210,226,120,124,86,51,21,51,9,183,218,70,13,255,253,145,75,124,168,233,205,183,88,208,233,150,163,32,224,194,147,47,226,65,138,58,152,49,93,33,144,251,14,24,169,177,0,79,192,247,211,139,203,181,89,135,69,255,56,245,26,132,122,223,168,252,206,20,184,56,232,58,57,108,0,195,68,0,161,139,108,119,131,57,101,229,238,97,157,185,13,242,135,69,152,21,242,74,138,176,90,192,55,95,180,220,201,73,5,199,230,235,226,247,142,231,125,241,44,211,222,163,151,198,228,163,89,236,22,238,157,209,52,141,63,178,240,63,196,26,24,223,55,164,2,4,0,173,3,2,1,1],"type":"Buffer"}}},"defaultPort":443,"freeSockets":{},"keepAlive":false,"keepAliveMsecs":1000,"maxCachedSessions":100,"maxFreeSockets":256,"maxSockets":null,"maxTotalSockets":null,"options":{"path":null},"protocol":"https:","requests":{},"scheduling":"fifo","sockets":{},"totalSocketCount":0}}},"path":"/api/v1/account/vehicles/VIN_HIDDEN/requests/32134404259","pathname":"/api/v1/account/vehicles/VIN_HIDDEN/requests/32134404259","port":null,"protocol":"https:"},"_redirectCount":0,"_redirects":[],"_requestBodyBuffers":[],"_requestBodyLength":0,"_writableState":{"afterWriteTickInfo":null,"autoDestroy":false,"bufferProcessing":false,"bufferedRequest":null,"bufferedRequestCount":0,"corked":0,"corkedRequestsFree":{"entry":null,"next":null},"decodeStrings":true,"defaultEncoding":"utf8","destroyed":false,"emitClose":true,"ended":false,"ending":false,"errorEmitted":false,"finalCalled":false,"finished":false,"highWaterMark":16384,"lastBufferedRequest":null,"length":0,"needDrain":false,"objectMode":false,"pendingcb":0,"prefinished":false,"sync":true,"writecb":null,"writelen"

**Comment by ehran** [comment]
Going through the closed issues, I found this quote : 

_@phildh it seems so, mine's been working without issue. I've found that API failures are generally expected especially after the car's been sitting for >12hrs but they eventually come back.

Post the full logs and I may be able to point something out.

_Originally posted by @michaelwoods in https://github.com/michaelwoods/onstar2mqtt/issues/45#issuecomment-878383828__

Let me thinking... I went through the logs of both cars (both Bolt EV 2017, one being used every day, the other sitting outside).

I realized that both cars were returning errors, the one sitting outside most of the time returning errors since a couple days non stop, the other one did not return errors until early this morning, after having been idle for 10+ hours, but went to normal messaging after it had been started this morning ... 

The second car, always returning errors for 2 days now, I found out I wasnt able to start it remotely from the myChevrolet app... and I wasnt even able to start it remotely with the remote key !!

I went into the car and started it manually, stopped it after a minute and.... all the errors disappeared... the logs are clean and have been for the last couple hours...

**Comment by ehran** [comment]
Continue to get error: Error {"error":{"request":{"authRequired" .... if the car has been sitting idle too long... any idea how to manage that ? Its also not defaulting to the latest statuses/values, all the board in HA to manage the EV gets errors.

Also, if trying to open the official myChevrolet app, I get logged off. When logging back on it takes forever to grab the updated data and just eventually fails...

**Comment by michaelwoods** [comment]
It's unlikely that a third-party library will be able to provide better reliability than a first-party app. I'm not sure of the cause but starting the vehicle does seem to reset or re-enable the API status for some time or amount of requests.

In a perfect world they'd provide real-time updates when on WiFi and/or wall powered. I wonder if the limitation is influenced by network costs or power savings.

**Comment by michaelwoods** [comment]
Both are limited by the API which is itself limited by the hardware in the car. Generally, if you don't drive it everyday (reducing update frequency may help) you'll lose connectivity.
