### ISSUE TITLE
Is there a "lock status" or "on/off status"?

### ISSUE THREAD

**Issue by skyw33** [michaelwoods/onstar2mqtt#192]
Is there any way to determine if the car is "on" or if the car is locked before sending a command to turn it on or lock it?

**Comment by BennyDaBee** [comment]
Is this an EV or a Gasoline/Petrol?

**Comment by skyw33** [comment]
EV

**Comment by michaelwoods** [comment]
Doesn't look like there is, sorry. The OnstarJS repo may be able to assist if that is in the API, but from memory I don't recall seeing any status like those.
