### ISSUE TITLE
Feature Request - Custom MQTT

### ISSUE THREAD

**Issue by nodiaque** [michaelwoods/onstar2mqtt#214]
Hello,

I notice everything is currently publish in HA format. I don't use HA, I use openhab. It would be great if a param could be set to change the mqtt path to something else then homeassistant. Also, maybe another one for the name instead of using the serial number?

Thank you!

**Comment by michaelwoods** [comment]
You can set the topic prefix: https://github.com/michaelwoods/onstar2mqtt/blob/main/src/index.js#L30

Define MQTT_PREFIX at runtime. You can also currently prefix the name value but it will still use the VIN in the topic.
