### ISSUE TITLE
"Too Many Requests"

### ISSUE THREAD

**Issue by charliesoap4** [michaelwoods/onstar2mqtt#222]
Is there any info on how often you can request info?  I've been getting errors ending with "status":429,"statusText":"Too Many Requests".  I have it on the default 30min refresh time.

**Comment by michaelwoods** [comment]
Sorry, I'm not aware of any. The biggest limitation is that the radio stops responding after some time that the vehicle is off. I'm not even sure what that is, but seems to be ~12-48hrs.
