### ISSUE TITLE
The Following Commands are Now "Forbidden" and Will Not Execute

### ISSUE THREAD

**Issue by BigThunderSR** [michaelwoods/onstar2mqtt#224]
Since earlier this week, the following commands are now returning a response of "status":403,"statusText":"Forbidden":

- startVehicle
- unlockDoor
- getLocation
- alert

The following still work:

- cancelStartVehicle
- lockDoor
- cancelAlert

Example:

error: Command error {"command":"startVehicle","err":{"message":"Request Failed with status 403 - Forbidden"

**Comment by nodiaque** [comment]
That explain why remote start doesn't work anymore :( I just added it to my google home, I like saying Hey Google, start the car!

**Comment by BennyDaBee** [comment]
@michaelwoods this is now fixed with newest onstarjs version.

**Comment by michaelwoods** [comment]
I merged the onstarjs PR. Last I checked github disabled automerging dependabot PRs, but if anyone is aware of an exclusion I would let OnstarJS auto-merge so fresh images are built with the new library version.
