### ISSUE TITLE
Failing randomly

### ISSUE THREAD

**Issue by nodiaque** [michaelwoods/onstar2mqtt#225]
Hello,
I'm looking at my log file and it seems I'm getting an error every now and there. When this happen, the sendCommand also stop working.

Here's what the log file show:
https://pastebin.com/0dnNrTcS

Restarting normally fix the issue, or just wait (sometime it takes many hours before it start working back).

Thank you

**Comment by michaelwoods** [comment]
That pastebin is a 200 success message indicating the command is in progress.

**Comment by nodiaque** [comment]
The first line is error with a "upgraderequire" somewhere in the line. It's all red in my log reader and when this happen, it's not updating on the mqtt side

**Comment by michaelwoods** [comment]
I see, it may be that the polling is reaching the timeout for command completion in the library. It shouldn't affect the command if so.

**Comment by nodiaque** [comment]
What I saw on my hand is I wake up and mqtt still say 25% charge but the car is at 65%, so nothing is updated. When I look at the log, I see this error on and on. Reboot the docker and it start working back. It's weird.

**Comment by michaelwoods** [comment]
Closing as typical API flakiness. Nothing we can do as consumers.
