### ISSUE TITLE
Data Does Not Refresh Even Though Manual Run of "diagnostics" Command Succeeds

### ISSUE THREAD

**Issue by BigThunderSR** [michaelwoods/onstar2mqtt#229]
Manually running the "diagnostics" command succeeds as seen in the onstar2mqtt log, but the data is not actually refreshed by onstar2mqtt. The only way to force a refresh successfully is to restart onstar2mqtt.

This seems to be similar to what is mentioned in https://github.com/michaelwoods/onstar2mqtt/issues/225#issuecomment-1310294316 although I am not seeing any errors as mentioned in that thread in the case where the command actually succeeds.

**Comment by michaelwoods** [comment]
The only (on-demand) command that is synchronous is the location command. As long as the response comes back from the API it should be easy to integrate the response handler for diagnostics too.

**Comment by charliesoap4** [comment]
Neither command actually publishes an mqtt message for me.  They both get "Command response data", but they don't actually _do_ anything.

**Comment by michaelwoods** [comment]
Closing as related bug was fixed.
