### ISSUE TITLE
Status 500 - Internal Server Error

### ISSUE THREAD

**Issue by UPEngineer** [michaelwoods/onstar2mqtt#233]
Hello,

Installed your image a few days ago and set it up in a docker image. Been running flawlessly on my 2022 GMC Acadia. I am able to start, lock/unlock doors, show tire pressures, etc.. 

That is until today. I tried to start my vehicle using my Home Assistant dashboard script (like always) and noticed a few minutes later that it didn't start. I am seeing the following message after running the docker container (I have removed my personal details and VIN #):

info: OnStar Config {"onstarConfig":{"allowCommands":true,"checkRequestStatus":true,"deviceId":"v4 UUID","onStarPin":"XXXX","password":"XXXXX","refreshInterval":1800000,"username":"user email","vin":"VIN NUMBER"}}
info: MQTT Config {"mqttConfig":{"host":"192.168.5.4","namePrefix":"","password":"mqtt_password","port":1883,"prefix":"homeassistant","tls":false,"username":"mqtt_user"}}
info: Requesting vehicles
info: Vehicle request status {"status":"success"}
info: Connecting to MQTT {"config":{"username":"mqtt_user","will":{"payload":"false","retain":true,"topic":"homeassistant/VIN NUMBER/available"}},"url":"mqtt://192.168.5.4:1883"}
info: Connected to MQTT
info: Subscribed to command topic {"topic":"homeassistant/VIN NUMBER/command"}
info: Requesting diagnostics
error: Error {"error":{"message":"Request Failed with status 500 - Internal Server Error","request":{"_closed":true,"_contentLength":383,"_defaultKeepAlive":true,"_ended":true,"_events":{},"_eventsCount":7,"_hasBody":true,"_header":"POST /api/v1/oauth/token/upgrade HTTP/1.1\r\nAccept: application/json\r\nContent-Type: text/plain\r\nAccept-Language: en-US\r\nHost: api.gm.com\r\nConnection: keep-alive\r\nAccept-Encoding: br, gzip, deflate\r\nUser-Agent: Mozilla/5.0 (Linux; U; Android 9; en-US; Google Pixel 2 Build/PI)\r\nAuthorization: Bearer

The last line is way longer, that is just a portion of it. I don;t see any other logs to look at. I completely re-created the docker container image and get the same results.

I'm at a loss. Any ideas to try?

Thanks,

Scott

**Comment by BigThunderSR** [comment]
Ditto. Looking like maybe GM is blocking this access method yet again. ☹️

**Comment by charliesoap4** [comment]
Same here.  It started not responding to lock/unlock/start commands a couple weeks ago with me, but was still getting diagnostics.  Now nothing and the same error as you.

**Comment by BigThunderSR** [comment]
Opened https://github.com/samrum/OnStarJS/issues/211 since any fixes/workarounds would need to happen there.

**Comment by BigThunderSR** [comment]
Things seem to be working again as of this morning.

**Comment by michaelwoods** [comment]
Doesn't seem to be working for me at the moment. I tried doubling the command timeout but still not receiving a diagnostics response.

**Comment by BigThunderSR** [comment]
Now I'm getting "403 - Forbidden" vs. the 500.

**Comment by BigThunderSR** [comment]
Things seem to be working again. 🤷‍♂️

**Comment by charliesoap4** [comment]
Yeah, now everything is working better than it was before for me. All the other commands are now working as well.

**Comment by andrewwm** [comment]
There's an updated terms of service that the app asks you to agree/deny. I'm not sure if that has to do anything with the failures reported. Obviously this project is a big no no: https://omnibus.gm.com/legal/contents/US/eula_default.pdf
