### ISSUE TITLE
getLocation response does not get sent back to MQTT

### ISSUE THREAD

**Issue by kate66** [michaelwoods/onstar2mqtt#250]
It appears that the getLocation command, after being returned, does not get sent to the MQTT broker to be send to device_tracker.

Logging output from the docker container:
`info: Command sent {"command":"getLocation"}
info: Command completed {"command":"getLocation"}
info: Command response data {"data":{"commandResponse":{"body":{"direction":{"uom":"degree","value":"0.0"},"location":{"lat":"42.0000000","long":"-71.0000000"},"speed":{"uom":"kmph","value":"0.0"}},"completionTime":"2023-01-26T05:44:53.336Z","requestTime":"2023-01-26T05:44:50.577Z","status":"success","type":"location","url":"https://api.gm.com:443/api/v1/account/vehicles/MY_VIN/requests/location12345678901234567890"}}}
info: Requesting diagnostics`

**Comment by kate66** [comment]
It looks like this bug was patched by somebody else -- Perhaps you can merge their change?
https://github.com/BigThunderSR/onstar2mqtt/commit/824831b7967031955a02a324ec8b543d02a28b14

**Comment by michaelwoods** [comment]
Merged the above fix and pushed 1.5.4. Please confirm, I no longer have the OnStar package for commands on my car.
