### ISSUE TITLE
API consistently returns error

### ISSUE THREAD

**Issue by tbclark3** [michaelwoods/onstar2mqtt#259]
THANK YOU for your work on this project!  I successfully configured it, and for about 24 hours it functioned correctly.  After that, it started returning "car did not respond errors."  I figured out that the car needed to be turned on, and it started working again, but only briefly.  For 2 days now, it has been consistently returning "unknown system error" (see sanitized json below).  I tried giving it a 1-day break, and changed the polling time to 4 hours when the car is garaged, and left it at 30 minutes when the car is out, but it hasn't helped.  My Android app is now also failing to update.  Both onstar2mqtt and the Android app correctly return the location. I'm not sure if this is a known problem, or if there has been a general outage at GM lasting several days, or if they have blocked my account.

{"error":{"message":"Command Failure","request":{"body":"{}","contentType":"application/json; charset=UTF-8","headers":{},"method":0,"url":"https://api.gm.com/api/v1/account/vehicles/XXXXXXXXXXXXXXXXX/requests/XXXXXXXXXXX"},"response":{"data":{"commandResponse":{"body":{"error":{"code":"ONS-900","description":"Unknown system error"}},"completionTime":"2023-03-15T12:22:31.184Z","requestTime":"2023-03-15T12:22:07.977Z","status":"failure","type":"diagnostics","url":"https://api.gm.com/api/v1/account/vehicles/XXXXXXXXXXXXXXXXX/requests/XXXXXXXXXXX"}},"headers":{"connection":"keep-alive","content-type":"application/json;charset=UTF-8","date":"Wed, 15 Mar 2023 12:22:34 GMT","request-context":"appId=cid-v1:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","transfer-encoding":"chunked"},"status":200,"statusText":"OK"},"stack":"Error: Command Failure\n    at RequestService.<anonymous> (/app/node_modules/onstarjs/dist/index.js:564:35)\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/onstarjs/dist/index.js:32:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}}

**Comment by michaelwoods** [comment]
If you don't run the car once or twice a day the radio stops responding. First party app suffers from this too.
