### ISSUE TITLE
Tire pressures are being converted incorrectly

### ISSUE THREAD

**Issue by jerry-knight** [michaelwoods/onstar2mqtt#269]
I think sometime recently the reported tire pressures in PSI are now showing values that are actually in kPa. All of my PSI values in `homeassistant/sensor/[VIN]/tire_pressure/state`  are now in the ~260 range, and 260 kPA is about 38 PSI. The standard non-PSI values are in the ~1800 range, so it really seems like all of the pressure values are getting an extra PSI-to-kPA conversion.

I don't see any open issues in OnstarJS, so I'm not sure whether I should submit this here or there. I see some unit conversions in the onstar2mqtt source, but it could be that OnstarJS is reporting the wrong units.

I'm currently running the latest docker image that reports version 1.5.5 in the logs.

**Comment by jerry-knight** [comment]
Submitted a corresponding issue to OnStarJS.

[OnStarJS Issue #219](https://github.com/samrum/OnStarJS/issues/219)

For now, I'm doing additional conversions to compensate.

**Comment by michaelwoods** [comment]
Noticed this too, but looks to be back to normal now.
