### ISSUE TITLE
Request Failed with status 400 - Bad Request

### ISSUE THREAD

**Issue by charliesoap4** [michaelwoods/onstar2mqtt#284]
19 hours ago, I started getting this error when requesting diagnostics.

> Request Failed with status 400 - Bad Request

...followed by hundreds of lines of gibberish.  I've restarted the container, as well as checked to make sure I can login with the My Chevrolet app.

**Comment by charliesoap4** [comment]
> 

I did, but yours give me a Status 500 Internal Server Error code.

**Comment by charliesoap4** [comment]
> That's just the OnStar API being itself and nothing to do with the code. 🙂
> 
> Give it some time and it will eventually decide it will respond to the requests.

Gotcha.  Thanks!

**Comment by michaelwoods** [comment]
v1.5.8 released with version bump
