### ISSUE TITLE
Since last update, it just die at requesting vehicle info

### ISSUE THREAD

**Issue by nodiaque** [michaelwoods/onstar2mqtt#285]
Hello,
Just found out that my docker container isn't running. When I start it, it stop in 5 sec. Log show it get to requesting vehicule information and exit right away.

![image](https://github.com/michaelwoods/onstar2mqtt/assets/324425/c817b455-6e0e-40dc-9def-903e70f4f3ae)

thank you

**Comment by nodiaque** [comment]
Ahhh... hurray for onstar..... make me rethink if I want a gm/chevrolet next car, this onstar service really suck.

**Comment by HaTaX2** [comment]
Looking at the changes made in the most recent update, it looks like when the myChevrolet app is updated a few config keys need to be updated to keep things working: 

https://github.com/samrum/OnStarJS/commit/81fbffc24d8e2fe76890a7450b4801efe0d13fd1

Looks like the last app build number they pulled was 4175 and the app version on my android device currently is 4181.
