### ISSUE TITLE
Request: Bump onstarjs to 2.3.26 and rebuild Docker container

### ISSUE THREAD

**Issue by mattdsteele** [michaelwoods/onstar2mqtt#305]
Hi, I'm running this module as a Docker container, and recently noticed all requests are failing with this error:

```
{"error":{"message":"Request Failed with status 400 - Bad Request",
```

This was when POSTing to `url: 'https://api.gm.com/api/v1/oauth/token'`

I also found I was getting something similar when running a test script with `onstarjs@2.3.22`. Updating to `2.3.26` (released a few days ago) resolved this issue for me. It appears the key was updated: https://github.com/samrum/OnStarJS/pull/231

Would you mind updating the package (I see a Dependabot PR out there already [going to 2.3.25](https://github.com/michaelwoods/onstar2mqtt/pull/302)) and push a new Docker container up?

Thank you!

**Comment by michaelwoods** [comment]
Build and publish in progress. Thanks for the notice.
