### ISSUE TITLE
ONSTAR EUrope

### ISSUE THREAD

**Issue by Rikardogonc** [michaelwoods/onstar2mqtt#323]
Hello I have an Opel Insignia B 2018, And now here in Europe we have lost access to Onstar, does this platform still work with Onstar inactive? I have my server I can share with you for testing or for the application to work. can anyone help? I can provide my car data to test if it works. Thanks. Please

**Comment by michaelwoods** [comment]
Sorry, without a service providing the data there is no direct car integration. Perhaps OBDII ports (this may just be North America) can provide data for the vehicle instead.

**Comment by Rikardogonc** [comment]
You can test?
I send vin for private message.
Because I think my car connect OnStar because sometimes led red turn green.
