### ISSUE TITLE
Force sensor update

### ISSUE THREAD

**Issue by mdezzi** [michaelwoods/onstar2mqtt#344]
Is there a way to force a sensor update or receive a response message after startVehicle is called? I have this integrated into Home Assistant and i'd like to confirm once the startVehicle command is called. Theoretically i can watch the "Engine RPM" topic to confirm that the vehicle has started, but it seems that the sensor sometimes doesnt update for a while. Is it possible to call the startVehicle, and then manually ask for a sensor update periodically?

**Comment by michaelwoods** [comment]
Someone's working on refactoring the commands now, keep an eye out for that when it lands.
