### ISSUE TITLE
Request Failed 400 on initial integration

### ISSUE THREAD

**Issue by jeffeb3** [michaelwoods/onstar2mqtt#347]
Hi,

I've read through some of the issues and I know `"Request Failed with status 400 - Bad Request"` is a common indicator that GM changed something or just an intermittent server issue. I've seen issue [233](https://github.com/samrum/OnStarJS/issues/233).

I'm setting this up for the first time, using new config values though, and I'm not sure if the issue is in my config, or the connection to onstar. Is there a way I can tell? I've ran the docker a few times in the last 12 hours. I'm pretty sure the username/password/pin/vin are right. I'm not 100% sure my mqtt settings are right (port/tls, for example).

Do you have any reason to think it would be down today and yesterday? I did get an email saying they were implementing MFA soon.

**Comment by Esprit1st** [comment]
My instance stopped working as well. Not sure when exactly since I was gone for a week.
Not sure where to find any logs.

**Comment by jeffeb3** [comment]
`docker logs onstar2mqtt` will give you the text log from npm. There is personal information in it, so be careful posting any of it.

**Comment by darrendavid** [comment]
Same issue here as well - it was working fine for a few months and stopped working on or around 2/21/24 for me as well. In looking at the JSON response I do see:

`"data": {
     "error": "invalid_client"
},`

so perhaps GM has locked down API access more tightly. 

Has anyone found an updated library or a workaround?

**Comment by jeffeb3** [comment]
I forgot to report back. The BigThunder version is working well for me. Onstar has its limitations. But this integration is impressive. I ended up installing it as an add on.

**Comment by darrendavid** [comment]
> I forgot to report back. The BigThunder version is working well for me. Onstar has its limitations. But this integration is impressive. I ended up installing it as an add on.

Just read back in the thread and BigThunder is working for me as well. Thank you @BigThunderSR!

**Comment by michaelwoods** [comment]
Pushed a build with the latest OnstarJS

**Comment by deboy69** [comment]
Pulled latest and im getting the error 400 bad request
