### ISSUE TITLE
Error 400 bad request

### ISSUE THREAD

**Issue by deboy69** [michaelwoods/onstar2mqtt#349]
Pulled latest with the following error. Generated a new UUID with no change.  there is more error logs upon request

info: Requesting vehicles
error: Main function error. {"error":{"message":"Request Failed with status 400 - Bad Request","request":{"_closed":true,"_contentLength":"457","_defaultKeepAlive":true,"_ended":true,"_events":{},"_eventsCount":7,"_hasBody":true,"_header":"POST /api/v1/oauth/token HTTP/1.1\r\nAccept: application/json\r\nContent-Type: text/plain\r\nAccept-Language: en\r\nHost: api.gm.com\r\nConnection: keep-alive\r\nAccept-Encoding: br, gzip, deflate\r\nUser-Agent: myChevrolet/118 CFNetwork/1408.0.4 Darwin/22.5.0\r\nContent-Length: 457\r\n\r\n","_headerSent":true,"_keepAliveTimeout":0,"_last":true,"_redirectable":{"_currentRequest":"[Circular]","_currentUrl":"https://api.gm.com/api/v1/oauth/token","_ended":true,"_ending":true,"_events":{},"_eventsCount":3,"_options":{"agents":{},"beforeRedirects":{},"headers":{"Accept":"application/json","Accept-Encoding":"br, gzip, deflate","Accept-Language":"en","Connection":"keep-alive","Content-Length":"457","Content-Type":"text/plain","Host":"api.gm.com","User-Agent":"myChevrolet/118 CFNetwork/1408.0.4 Darwin/22.5.0"},"hostname":"api.gm.com","maxBodyLength":null,"maxRedirects":21,"method":"POST","nativeProtocols":{"http:":{"ME

**Comment by arnpag** [comment]
It looks like I'm getting the same error after pulling and starting. After inspecting the large json object that it returns, the only clue I can find is this section in the response portion:
`"data":{
    "error":"invalid_client"
},`
It looks like it's an oauth issue, but I'm no oauth expert so I'm not sure.

**Comment by michaelwoods** [comment]
Pushed a version bump. I'll have to switch the docker build from `ci` so the weekly build will evergreen the onstarjs version.

**Comment by deboy69** [comment]
Pulled latest and getting the following error again.

error: Main function error. {"error":{"message":"No response","request":{"_currentRequest":{"_closed":false,"_contentLength":"457","_defaultKeepAlive":true,"_ended":false,"_events":{},"_eventsCount":7,"_hasBody":true,"_header":"POST /api/v1/oauth/token HTTP/1.1\r\nAccept: application/json\r\nContent-Type: text/plain\r\nAccept-Language: en\r\nHost: api.gm.com\r\nConnection: keep-alive\r\nAccept-Encoding: br, gzip, deflate\r\nUser-Agent: myChevrolet/118 CFNetwork/1408.0.4 Darwin/22.5.0\r\nContent-Length: 457\r\n\r\n","_headerSent":true,"_keepAliveTimeout":0,"_last":true,"_redirectable":"[Circular]","_removedConnection":false,"_removedContLen":false,"_removedTE":false,"_trailer":"","aborted":false,"agent":{"_events":{},"_eventsCount":2,"_sessionCache":{"list":[],"map":{}},"defaultPort":443,"freeSockets":{},"keepAlive":false,"keepAliveMsecs":1000,"maxCachedSessions":100,"maxFreeSockets":256,"maxSockets":null,"maxTotalSockets":null,"options":{"noDelay":true,"path":null},"protocol":"https:","requests":{},"scheduling":"lifo","sockets":{"api.gm.com:443:::::::::::::::::::::":[{"_SNICallback":null,"_closeAfterHandlingError":false,"_controlReleased":true,"_events":{"close":[null,null,null,null,null],"connect":[null,null,null],"end":[null,null]},"_eventsCount":11,"_hadError":true,"_host":"api.gm.com","_httpMessage":"[Circular]","_newSessionPending":false,"_parent":null,"_pendingData":[{"chunk":"POST /api/v1/oauth/token HTTP/1.1\r\nAccept: application/json\r\nContent-Type: text/plain\r\nAccept-Language: en\r\nHost: api.gm.com\r\nConnection: keep-alive\r\nAccept-Encoding: br, gzip, deflate\r\nUser-Agent: myChevrolet/118 CFNetwork/1408.0.4 Darwin/22.5.0\r\nContent-Length: 457\r\n\r\n","encoding":"latin
