### ISSUE TITLE
error: Main function error. {"error":{}}

### ISSUE THREAD

**Issue by glassbase** [michaelwoods/onstar2mqtt#63]
Hi,

I am trying to run the docker container. Here is the docker logs I get before the container crashes/stops.

```
> onstar2mqtt@1.2.3 start /app
> node src/index.js

info: OnStar Config {"onstarConfig":{"deviceId":"OMIT","username":"OMIT","password":"OMIT","onStarPin":"OMIT","checkRequestStatus":true,"refreshInterval":1800000,"allowCommands":true}}
info: MQTT Config {"mqttConfig":{"host":"10.0.0.8","username":"","password":"","port":1883,"tls":false,"prefix":"homeassistant/onstar"}}
error: Main function error. {"error":{}}
```
***this repeats twice before the containers crashes/stops

Is there a debug flag or something else to help debug?

Could it be that my MQTT server does not require a user/pass?

Any help would be appreciated, thanks.

**Comment by phildh** [comment]
I had this error once before as well, it was my MQTT add-on in home-assistant. I had to remove it and reconfigure it. I found this out by setting up a stand a long server and pointing docker image to that. Your MQTT should have username/password required, I would not set it up without one, I use the home assistant add on and use those. Based on log below, it looks like youre not passing the username/password for MQTT unless you omitted it:

info: MQTT Config {"mqttConfig":{"host":"10.0.0.8","username":"","password":"","port":1883,"tls":false,"prefix":"homeassistant/onstar"}}
error: Main function error. {"error":{}}

**Comment by glassbase** [comment]
I do run a standalone MQTT server. Always have. 

I am passing a blank one via env file. Also tried omitting the variables from env, same error.

**Comment by glassbase** [comment]
I reconfigured MQTT with user and password. Still have error. Any way to debug?

**Comment by glassbase** [comment]
My mistake. Typo in env file. I had `ONSTAR_VINxxxxxxxxx` instead of `ONSTAR_VIN=xxxxxxxxx` (missing the equal sign). 

Working now, thanks
