### ISSUE TITLE
Feature Request - Location

### ISSUE THREAD

**Issue by glassbase** [michaelwoods/onstar2mqtt#87]
I requested the location command feature be added into OnStarJS. 

https://github.com/samrum/OnStarJS/pull/149

Is it possible to integrate it into your project as well?

Awesome work, thanks.

**Comment by sspencer10** [comment]
I just seen that and was coming here to request the same thing!

**Comment by michaelwoods** [comment]
Added this in the latest main branch. There's some manual configuration required and I opted to trigger updates with a manual command as I don't know what (if any) implications there are from frequent location requests.

Configure your entities and scripts/automations and it should be working. My car shows up properly and tagged in the correct zone.
